"""empty message

Revision ID: 40ec7e6174c5
Revises: 447103ab9e76
Create Date: 2024-02-09 03:44:38.432189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ec7e6174c5'
down_revision = '447103ab9e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('distancia',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('distancia',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
