"""empty message

Revision ID: 447103ab9e76
Revises: 35e0ce852d53
Create Date: 2024-02-09 03:43:49.590238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447103ab9e76'
down_revision = '35e0ce852d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)

    # ### end Alembic commands ###
