"""empty message

Revision ID: 44b0c3eb4527
Revises: 5fac0b41c4f7
Create Date: 2024-01-30 17:44:19.319361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b0c3eb4527'
down_revision = '5fac0b41c4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_ciudad', sa.String(length=45), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_ruta', sa.String(length=45), nullable=False),
    sa.Column('distancia', sa.String(length=20), nullable=False),
    sa.Column('tiempo_de_recorrido', sa.String(length=20), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('por__visitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitada', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_ruta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('por__visitar')
    op.drop_table('rutas')
    op.drop_table('ciudad')
    # ### end Alembic commands ###
