"""empty message

Revision ID: 45f2f630f749
Revises: 057c59b989f8
Create Date: 2024-02-15 18:36:37.772786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f2f630f749'
down_revision = '057c59b989f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
