"""empty message

Revision ID: 58af24be55a6
Revises: bc461a01c7aa
Create Date: 2024-02-09 03:41:44.893463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58af24be55a6'
down_revision = 'bc461a01c7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('distancia',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.alter_column('distancia',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
