"""empty message

Revision ID: a60027365511
Revises: b683057ca5ef
Create Date: 2024-01-29 17:34:58.703720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60027365511'
down_revision = 'b683057ca5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_registro', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('pais_de_residencia', sa.String(length=45), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pais_de_residencia')
        batch_op.drop_column('fecha_de_registro')

    # ### end Alembic commands ###
