"""empty message

Revision ID: b683057ca5ef
Revises: 46335533e03d
Create Date: 2024-01-29 17:27:49.337344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b683057ca5ef'
down_revision = '46335533e03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=45), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=45), nullable=False))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('edad')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
