"""empty message

Revision ID: d4afa93fe612
Revises: 
Create Date: 2024-02-13 00:50:39.432564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4afa93fe612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_pais', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_de_pais')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('apellidos', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('fecha_de_registro', sa.String(length=10), nullable=False),
    sa.Column('pais_de_residencia', sa.String(length=45), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_ciudad', sa.String(length=45), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_ruta', sa.String(length=45), nullable=False),
    sa.Column('distancia', sa.String(length=10), nullable=False),
    sa.Column('imagen', sa.String(length=400), nullable=True),
    sa.Column('tiempo_de_recorrido', sa.String(length=20), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('por__visitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitada', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_ruta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('por__visitar')
    op.drop_table('rutas')
    op.drop_table('ciudad')
    op.drop_table('user')
    op.drop_table('pais')
    # ### end Alembic commands ###
